---
service:
  rest:
    port: :8081
  grpc:
    port: :8082
connection:
  nosql:
    type: MongoDB
    localhost: http://localhost:27017
    cluster: false
#    host: 127.0.0.1
#    port: "27017"
#    username: admin
#    password: admin
#    database: studio
#    replicaset: Sandbox-shard-0
